import XCTest
@testable import LuminaLog

/// Cross-platform embedding PARITY gate (plan §1c-RAG "Phase 0"). This is the check
/// that must pass BEFORE `DevFlags.aiModel1` is flipped on and any real vector is
/// written to the encrypted store — because the 768-dim and the embedding semantics
/// lock the moment production vectors exist, and a mismatched on-device pipeline
/// (wrong tokenizer, double-pooling, wrong ONNX output) would silently poison search
/// and break Step-2 web/Android comparability.
///
/// It embeds the shared `scripts/embedding-parity/texts.json` on device via the REAL
/// production path (`LazyONNXTextEmbedder` → download+verify → `ONNXTextEmbedder`) and
/// asserts cosine > 0.999 against the Transformers.js reference vectors generated by
/// `scripts/embedding-parity/reference.mjs`.
///
/// ## Opt-in only (skips by default)
/// This is an integration test: it downloads the ~200 MB model and runs ONNX, so it
/// does NOT run in the normal unit suite. It runs only when BOTH hold:
///   * the model is hosted — `AppConfig.embeddingModelAsset` (+ tokenizer assets) is
///     non-nil (the six Info.plist keys are filled), and
///   * `EMBEDDING_PARITY_REFERENCE` env var points at the `reference_vectors.json`
///     produced by `reference.mjs`.
/// Otherwise it `XCTSkip`s, so it is green (and self-documenting) until you host the
/// model and choose to run the gate.
final class EmbeddingParityTests: XCTestCase {

    private struct Reference: Decodable {
        let model: String
        let dimension: Int
        let texts: [String]
        let vectors: [[Float]]
    }

    /// Minimum acceptable cosine similarity between the on-device vector and the web
    /// reference for the same text (plan gate: > 0.999).
    private let threshold: Float = 0.999

    func testOnDeviceEmbeddingsMatchWebReference() async throws {
        let env = ProcessInfo.processInfo.environment
        guard let refPath = env["EMBEDDING_PARITY_REFERENCE"], !refPath.isEmpty else {
            throw XCTSkip("Set EMBEDDING_PARITY_REFERENCE=<reference_vectors.json> to run the parity gate.")
        }

        // Two embedder sources:
        //  * EMBEDDING_LOCAL_MODEL_DIR (a folder with the .onnx + tokenizer.json +
        //    tokenizer_config.json) → validate a model on disk BEFORE hosting.
        //  * otherwise the real hosted path (LazyONNXTextEmbedder via AppConfig).
        let embedder: TextEmbedder
        if let localDir = env["EMBEDDING_LOCAL_MODEL_DIR"], !localDir.isEmpty {
            let dir = URL(fileURLWithPath: localDir, isDirectory: true)
            let onnx = try FileManager.default.contentsOfDirectory(atPath: localDir)
                .first { $0.hasSuffix(".onnx") }
            let modelURL = dir.appendingPathComponent(try XCTUnwrap(onnx, "no .onnx in \(localDir)"))
            embedder = ONNXTextEmbedder(modelURL: modelURL, tokenizerDirectory: dir)
        } else {
            guard let modelAsset = AppConfig.embeddingModelAsset,
                  let tokenizerAsset = AppConfig.embeddingTokenizerAsset,
                  let tokenizerConfigAsset = AppConfig.embeddingTokenizerConfigAsset else {
                throw XCTSkip("Embedding model not hosted (Info.plist keys blank) — parity gate skipped.")
            }
            embedder = LazyONNXTextEmbedder(
                modelAsset: modelAsset,
                tokenizerAsset: tokenizerAsset,
                tokenizerConfigAsset: tokenizerConfigAsset
            )
        }

        let refData = try Data(contentsOf: URL(fileURLWithPath: refPath))
        let reference = try JSONDecoder().decode(Reference.self, from: refData)
        XCTAssertEqual(reference.dimension, EmbeddingVector.dimension,
                       "reference dimension must match the app's locked 512-dim")
        XCTAssertEqual(reference.texts.count, reference.vectors.count)

        var worst: Float = 1
        for (index, text) in reference.texts.enumerated() {
            let onDevice = try await embedder.embed(text)
            let refVector = EmbeddingVector(reference.vectors[index])
            let cosine = try XCTUnwrap(
                onDevice.cosineSimilarity(to: refVector),
                "degenerate vector for text #\(index)"
            )
            worst = min(worst, cosine)
            XCTAssertGreaterThan(
                cosine, threshold,
                "text #\(index) parity cosine \(cosine) ≤ \(threshold): on-device pipeline diverges from the web reference — \(text)"
            )
        }
        NSLog("PARITY worst cosine = \(worst) across \(reference.texts.count) texts")
    }
}
