import { describe, it, expect } from 'vitest'
import { embed, cosineSimilarity } from '@/lib/embeddings/onnxEmbedder'
import ref from '@/lib/embeddings/__fixtures__/reference_vectors.json'

// Cross-platform parity gate. `reference_vectors.json` is the canonical distiluse
// 512-dim reference generated by running the SAME hosted ONNX under
// onnxruntime-node (scripts/gen-distiluse-reference.mjs) — the graph iOS validated
// against Python sentence-transformers at 0.9999991. This asserts the web path
// (Transformers.js tokenizer + onnxruntime-web + L2) reproduces that space.
//
// ⚠️ If this fails, DO NOT write web vectors to the shared /v1/vectors store —
// the 512-dim space would be corrupted. Fix tokenization / output selection first.
//
// Opt-in: downloads the 258 MB ONNX (cached after first run) and takes ~45s, so
// it is skipped in the default suite. Run it deliberately before shipping:
//   PARITY_GATE=1 npx vitest run src/lib/embeddings/onnxEmbedder.parity.test.ts
const GATE_ENABLED = process.env.PARITY_GATE === '1'

describe.skipIf(!GATE_ENABLED)('embed — cross-platform parity gate', () => {
  it('matches the canonical distiluse 512-dim reference at cosine > 0.999 for every shared text', async () => {
    expect(ref.dimension).toBe(512)
    for (let i = 0; i < ref.texts.length; i++) {
      const v = await embed(ref.texts[i])
      expect(v).toHaveLength(512)
      const cos = cosineSimilarity(Array.from(v), ref.vectors[i])
      expect(cos, `text #${i}: "${ref.texts[i].slice(0, 40)}…"`).toBeGreaterThan(0.999)
    }
  }, 180_000)
})
