import Foundation
import OSLog

/// Drives the Journal Detail screen (design §4): live entry stream plus the
/// three AI actions (summary, insights, prompts) with exactly-one-in-flight
/// guards.
///
/// Persistence note: after every successful generation the result is written
/// back via `repository.updateAIFields`, which updates only the generated
/// field and fails (rather than recreating the document) when the entry was
/// deleted mid-generation. The production proxy ALSO persists server-side
/// (spec §4.1); this client-side write is for instant UI consistency and for
/// demo mode, where `MockAIService` does not write back to the repository.
@MainActor
final class JournalDetailViewModel: ObservableObject {

    private static let logger = Logger(subsystem: "com.konradgnat.luminalog", category: "journal-detail")

    // MARK: - Published state

    /// The live entry — nil before the first emission and after deletion.
    @Published private(set) var entry: JournalEntry?

    @Published private(set) var summaryState: AIActionState = .idle
    /// State of the failed-transcript "Retry" action (voice/video entries
    /// whose on-device STT failed at create time).
    @Published private(set) var transcriptRetryState: AIActionState = .idle

    /// True once the first stream emission has landed (so the view can tell
    /// "loading" apart from "entry not found").
    @Published private(set) var hasLoaded = false

    /// Set true once the entry has been deleted so the view can pop.
    @Published private(set) var didDelete = false

    let entryId: String

    private let journals: JournalRepository
    private let profiles: ProfileRepository
    private let ai: AIService
    private let media: MediaUploader

    private var liveTask: Task<Void, Never>?
    private var hasStarted = false
    /// Latches once auto-generation has produced this entry's AI, so the summary
    /// is generated AT MOST ONCE per session — a single LLM call. Without it a
    /// live snapshot that momentarily lacks AI (e.g. a racing full-document save)
    /// could retrigger a wasteful re-generation. Reset on failure so a transient
    /// error can still be retried. The manual "Regenerate" action bypasses this.
    private var hasAutoGenerated = false

    init(
        entryId: String,
        journals: JournalRepository,
        ai: AIService,
        media: MediaUploader? = nil,
        profiles: ProfileRepository? = nil
    ) {
        self.entryId = entryId
        self.journals = journals
        self.ai = ai
        // Fallbacks are constructed inside this @MainActor init (legal), so the
        // media/profiles arguments stay optional for tests that don't exercise
        // those paths. Production (`JournalDetailView`) passes both explicitly.
        self.media = media ?? MockMediaUploader()
        self.profiles = profiles ?? MockProfileRepository()
    }

    deinit {
        liveTask?.cancel()
    }

    // MARK: - Lifecycle

    /// Awaits the first snapshot, starts live updates, then lazily generates
    /// the summary when the entry has none (spec §5.1: "summary generated on
    /// first open of detail view if nil"). Idempotent.
    func start() async {
        guard !hasStarted else { return }
        hasStarted = true

        // One-shot read: streams emit the current value immediately, so the
        // initial state is settled by the time this returns (testable).
        for await first in journals.entry(id: entryId) {
            entry = first
            break
        }
        hasLoaded = true

        startLiveUpdates()
        await generateSummaryIfMissing()
    }

    private func startLiveUpdates() {
        liveTask = Task { [weak self] in
            guard let stream = self?.journals.entry(id: self?.entryId ?? "") else { return }
            for await entry in stream {
                guard let self, !Task.isCancelled else { return }
                self.entry = entry
                // Generate the entry's AI when content is present but none exists
                // yet — e.g. a voice/video transcript that arrives after the view
                // opened. The `hasAutoGenerated` latch inside `generateSummaryIfMissing`
                // makes this fire at most once, so a later snapshot that momentarily
                // lacks AI (a racing full-document save) can't retrigger it.
                if let entry, !entry.content.isEmpty, entry.summary == nil {
                    Task { await self.generateSummaryIfMissing() }
                }
            }
        }
    }

    // MARK: - Summary

    /// True when the entry's text was edited after its summary was generated
    /// — gates the "Regenerate" affordance on the summary card (design §4).
    var isSummaryStale: Bool {
        guard
            let entry,
            let summary = entry.summary,
            let editedAt = entry.contentEditedAt
        else { return false }
        return editedAt > summary.generatedAt
    }

    private func generateSummaryIfMissing() async {
        // At most one auto-generation per session — a single LLM call. `start()`
        // and the live-update listener both funnel through here, and a racing
        // full-document save can transiently null the AI fields; the latch stops
        // any of that from spending a second call.
        guard !hasAutoGenerated else { return }
        guard let entry, !entry.content.isEmpty else { return }
        // On the ZK path a missing summary OR missing insights/prompts triggers a
        // (re)generation, since all three come from one client call — this also
        // backfills entries that got a summary-only from the earlier client path.
        let missingSummary = entry.summary == nil
        let missingEntryAI = DevFlags.aiModel1 && (entry.insights == nil || entry.prompts == nil)
        guard missingSummary || missingEntryAI else { return }
        // Latch before awaiting so a concurrent listener emission can't slip a
        // second call in; release it if the generation fails so a retry is allowed.
        hasAutoGenerated = true
        await generateSummary()
        if summaryState == .failed { hasAutoGenerated = false }
    }

    func generateSummary() async {
        guard summaryState != .loading, entry != nil else { return }
        summaryState = .loading
        do {
            if DevFlags.aiModel1 {
                // Zero-knowledge: the server can't index migrated entries, so generate
                // summary + insights + prompts client-side in one call and persist all
                // three (client-encrypted). This lights up the Insights/Prompts tabs.
                let bundle = try await ai.generateEntryAI(journalId: entryId)
                try await persist(bundle: bundle)
            } else {
                let generation = try await ai.generateSummary(journalId: entryId)
                try await persist(summary: generation)
            }
            summaryState = .idle
        } catch {
            Self.logger.error("generateSummary failed: \(error.localizedDescription, privacy: .public)")
            summaryState = .failed
        }
    }

    // Insights and follow-up prompts are generated server-side together with the
    // summary at index time and stored on the entry; the client only displays
    // them (see `JournalDetailView.insightsTab` / `promptsTab`). There is no
    // client-side generation path for them.

    // MARK: - Transcript retry

    /// Re-transcribes a voice/video entry. On the zero-knowledge (Model-1) path the
    /// server can't decrypt the audio, so we re-fetch the entry's audio from S3,
    /// decrypt it on-device (`media.localFileURL`), transcribe via the stateless
    /// clip endpoint (Together Whisper), and write the transcript + `.ready` status
    /// back through the repository (which re-indexes it). The live listener refreshes
    /// the UI. (Off the ZK path this would defer to server-side Whisper — but that
    /// path no longer exists.)
    func retryTranscription() async {
        guard transcriptRetryState != .loading, let entry else { return }
        guard entry.type == .voice || entry.type == .video else { return }

        transcriptRetryState = .loading
        do {
            // Prefer the audio attachment; fall back to a video file's audio track.
            guard let clip = entry.media.first(where: { $0.kind == .audio })
                ?? entry.media.first(where: { $0.kind == .video }) else {
                transcriptRetryState = .failed
                return
            }
            let fileURL = try await media.localFileURL(for: clip.s3Key)
            let data = try Data(contentsOf: fileURL)
            let transcript = try await ai.transcribeClip(audio: data, contentType: "audio/m4a")
                .trimmingCharacters(in: .whitespacesAndNewlines)

            var updated = entry
            let oldWordCount = entry.wordCount
            updated.content = transcript
            updated.transcriptStatus = transcript.isEmpty ? .failed : .ready
            updated.wordCount = WordCount.of(transcript)
            try await journals.save(updated)
            self.entry = updated
            // Credit the word delta to the lifetime odometer (best-effort). The
            // day's goal progress + streak are reconciled from today's entries by
            // the app-level DailyGoalReconciler, so a failed-then-retried
            // transcription now correctly raises today's count.
            if updated.wordCount != oldWordCount {
                try? await profiles.addTotalWords(delta: updated.wordCount - oldWordCount)
            }
            transcriptRetryState = transcript.isEmpty ? .failed : .idle
        } catch {
            Self.logger.error("retryTranscription failed: \(error.localizedDescription, privacy: .public)")
            transcriptRetryState = .failed
        }
    }

    // MARK: - Exclude from share

    func setExcludeFromShare(_ value: Bool) {
        guard var e = entry else { return }
        e.excludeFromShare = value
        entry = e
        Task { try? await journals.setExcludeFromShare(entryId: e.id, value: value) }
    }

    // MARK: - Delete

    /// Best-effort delete: purge remote artifacts (S3 media + embeddings +
    /// summary) server-side, then always remove the Firestore record so the
    /// entry disappears from the user's list (spec delete policy).
    func delete() async {
        guard let deleted = entry else { return }
        do {
            try await ai.deleteEntry(journalId: entryId)
        } catch {
            Self.logger.error("""
            remote delete cleanup failed for \(self.entryId, privacy: .private); \
            removing record anyway: \(error.localizedDescription, privacy: .public)
            """)
        }
        do {
            try await journals.delete(id: entryId)
        } catch {
            Self.logger.error("""
            firestore delete failed for \(self.entryId, privacy: .private): \
            \(error.localizedDescription, privacy: .public)
            """)
        }
        // Remove the deleted words from the lifetime odometer (best-effort). The
        // day's goal progress + streak reconcile from today's entries via the
        // app-level DailyGoalReconciler.
        if deleted.wordCount != 0 {
            try? await profiles.addTotalWords(delta: -deleted.wordCount)
        }
        didDelete = true
    }

    // MARK: - Persistence

    /// Writes the newly generated summary through to the repository
    /// (field-scoped, so a deleted entry is never recreated), then mirrors it
    /// onto the local snapshot for instant UI (see class docs).
    ///
    /// Only the summary is written client-side; insights and prompts are owned
    /// by the server (generated + stored at index time). A not-found failure
    /// means the entry was deleted mid-generation: the result is dropped
    /// silently — the live stream has already (or will) set `entry` to nil, so
    /// the view shows "Entry not found".
    private func persist(summary: AIGeneration) async throws {
        guard var updated = entry else { return }
        do {
            try await journals.updateAIFields(
                id: entryId,
                summary: summary,
                insights: nil,
                prompts: nil
            )
        } catch JournalRepositoryError.entryNotFound {
            Self.logger.notice("""
            entry \(self.entryId, privacy: .private) deleted mid-generation; \
            dropping AI result instead of recreating it
            """)
            return
        }
        updated.summary = summary
        entry = updated
    }

    /// Zero-knowledge counterpart to `persist(summary:)`: writes the client-generated
    /// summary + insights + prompts through the repository (client-encrypted) and
    /// mirrors them onto the local snapshot so all three tabs light up immediately.
    private func persist(bundle: EntryAIBundle) async throws {
        guard var updated = entry else { return }
        do {
            try await journals.updateAIFields(
                id: entryId,
                summary: bundle.summary,
                insights: bundle.insights,
                prompts: bundle.prompts
            )
        } catch JournalRepositoryError.entryNotFound {
            Self.logger.notice("""
            entry \(self.entryId, privacy: .private) deleted mid-generation; \
            dropping AI result instead of recreating it
            """)
            return
        }
        updated.summary = bundle.summary
        updated.insights = bundle.insights
        updated.prompts = bundle.prompts
        entry = updated
    }
}
