'use client'

import Image from 'next/image'
import { INK, CREAM, MUTE, ACCENT, HAIRLINE } from './theme'

type Card =
  | { kind: 'image'; src: string; alt: string; caption: string }
  | { kind: 'text'; eyebrow: string; body: string; caption: string }

const CARDS: Card[] = [
  {
    kind: 'image',
    src: '/landing/shot-insight-card.webp',
    alt: 'A real Daily Insights card generated by Argo, including its gem haiku',
    caption: 'A real Daily Insights card. Generated the moment you cross 750 words.',
  },
  {
    kind: 'text',
    eyebrow: 'The gem',
    body: 'An idea born, takes shape in voice\nand silence,\na gift to the world.',
    caption: 'A real gem from that card: a three-line haiku distilled from a real day of writing, abstracted so it is safe to share.',
  },
  {
    kind: 'text',
    eyebrow: 'What is on the card',
    body: 'An insight. A new perspective. One question worth sitting with. Your streak, your word count, and the emotional texture of the day.',
    caption: 'All grounded in what you actually wrote that day.',
  },
  {
    kind: 'text',
    eyebrow: 'Yours to keep',
    body: 'Tap Share to send it to Messages, Instagram, or anywhere else. Nothing leaves your device unless you choose to send it.',
    caption: 'Sharing is always your call, never automatic.',
  },
]

export default function InsightsCarousel() {
  return (
    <section id="reflect" style={{ background: INK, color: CREAM, padding: '120px 0' }}>
      <div className="wrap">
        <span style={{ fontSize: 13, fontWeight: 700, letterSpacing: '0.14em', textTransform: 'uppercase', color: ACCENT }}>
          The payoff
        </span>
        <h2 className="serif" style={{ marginTop: 14, fontSize: 'clamp(30px, 4vw, 46px)', fontWeight: 600 }}>
          Get the highlights.
        </h2>
        <p style={{ marginTop: 12, fontSize: 17, color: MUTE, maxWidth: 520 }}>
          The moment you hit 750 words, Argo reads the day and hands you something back.
        </p>

        {/* A grid inside the page column, not a scroller: all four cards sit in
         * one row on desktop. The screenshot is a tall phone capture, so it
         * gets a fixed-height tile instead of setting the row's height. */}
        <div
          style={{
            marginTop: 48,
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))',
            gap: 16,
          }}
        >
          {CARDS.map((card, i) => (
            <div
              key={i}
              style={{
                borderRadius: 22,
                border: `1px solid ${HAIRLINE}`,
                background: 'rgba(255,255,255,0.03)',
                overflow: 'hidden',
                display: 'flex',
                flexDirection: 'column',
              }}
            >
              {card.kind === 'image' ? (
                <div style={{ position: 'relative', height: 300, margin: '16px 16px 0' }}>
                  <Image src={card.src} alt={card.alt} fill unoptimized style={{ objectFit: 'contain' }} />
                </div>
              ) : (
                <div style={{ padding: '22px 18px 0', flex: 1 }}>
                  <span style={{ display: 'block', fontSize: 12, lineHeight: 1.4, fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: ACCENT }}>
                    {card.eyebrow}
                  </span>
                  <p className="serif" style={{ marginTop: 12, fontSize: 'clamp(15px, 1.6vw, 17px)', lineHeight: 1.5, whiteSpace: 'pre-line', fontStyle: 'italic' }}>
                    {card.body}
                  </p>
                </div>
              )}
              <p style={{ padding: '12px 18px 18px', fontSize: 13.5, lineHeight: 1.5, color: MUTE }}>{card.caption}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
