'use client'

import Image from 'next/image'
import { INK, CREAM, MUTE, ACCENT, HAIRLINE } from './theme'

type Card =
  | { kind: 'image'; src: string; alt: string; caption: string }
  | { kind: 'text'; eyebrow: string; body: string; caption: string }

const CARDS: Card[] = [
  {
    kind: 'image',
    src: '/demo-day/shot-insight-card.png',
    alt: 'A real Daily Insights card generated by Argo, including its gem haiku',
    caption: 'A real Daily Insights card. Generated the moment you cross 750 words.',
  },
  {
    kind: 'text',
    eyebrow: 'The gem',
    body: 'An idea born, takes shape in voice\nand silence,\na gift to the world.',
    caption: 'A real gem from that card: a three-line haiku distilled from a real day of writing, abstracted so it is safe to share.',
  },
  {
    kind: 'text',
    eyebrow: 'What is on the card',
    body: 'An insight. A new perspective. One question worth sitting with. Your streak, your word count, and the emotional texture of the day.',
    caption: 'All grounded in what you actually wrote that day.',
  },
  {
    kind: 'text',
    eyebrow: 'Yours to keep',
    body: 'Tap Share to send it to Messages, Instagram, or anywhere else. Nothing leaves your device unless you choose to send it.',
    caption: 'Sharing is always your call, never automatic.',
  },
]

export default function InsightsCarousel() {
  return (
    <section id="reflect" style={{ background: INK, color: CREAM, padding: '120px 0' }}>
      <div className="wrap">
        <span style={{ fontSize: 13, fontWeight: 700, letterSpacing: '0.14em', textTransform: 'uppercase', color: ACCENT }}>
          The payoff
        </span>
        <h2 className="serif" style={{ marginTop: 14, fontSize: 'clamp(30px, 4vw, 46px)', fontWeight: 600 }}>
          Get the highlights.
        </h2>
        <p style={{ marginTop: 12, fontSize: 17, color: MUTE, maxWidth: 520 }}>
          The moment you hit 750 words, Argo reads the day and hands you something back.
        </p>
      </div>

      <div style={{ marginTop: 48, display: 'flex', gap: 24, overflowX: 'auto', scrollSnapType: 'x mandatory', padding: '4px 24px 24px' }}>
        {CARDS.map((card, i) => (
          <div
            key={i}
            style={{
              scrollSnapAlign: 'start',
              flex: '0 0 min(78vw, 360px)',
              borderRadius: 28,
              border: `1px solid ${HAIRLINE}`,
              background: 'rgba(255,255,255,0.03)',
              overflow: 'hidden',
              display: 'flex',
              flexDirection: 'column',
            }}
          >
            {card.kind === 'image' ? (
              <Image src={card.src} alt={card.alt} width={462} height={1000} style={{ width: '100%', height: 'auto', display: 'block' }} />
            ) : (
              <div style={{ padding: '32px 26px', minHeight: 300, display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
                <span style={{ fontSize: 12, fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: ACCENT }}>
                  {card.eyebrow}
                </span>
                <p className="serif" style={{ marginTop: 14, fontSize: 20, lineHeight: 1.5, whiteSpace: 'pre-line', fontStyle: 'italic' }}>
                  {card.body}
                </p>
              </div>
            )}
            <p style={{ padding: '16px 20px 22px', fontSize: 14, lineHeight: 1.5, color: MUTE }}>{card.caption}</p>
          </div>
        ))}
      </div>
    </section>
  )
}
